authorized_keys:
  - user: ETBE-key
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeuQuI9G3+Dkg1S7V+zIDxbKk9NUz8oPFs6/lhHxCcWdiVJB82vvSEgXeRbEwaZdZzQeKh6YoO/kb8YQjvUjvpDALNXyuRiWf5gasZG8fIfpSKbmnjXXaxB4xoURrkWUzL9BXtrBmiZTaIYZb3fMeJc/3EO7cVtROFLvwedD/PAgkOQjOn+UAOIlsi/kCBQ0Jah6BYX6cQH+OH9PuZIeCKRLt0nghh7spNQTFZ6D/ftaBVMsYc64ZGhqrk908Uuoh2tVxI7ow1lBZyFhwOlyNqtC/tn/zdVBUHFFmEt+1C21crewt3rxembRAZfCwn2cm/HuplEQXU08i4kxMuVXFJ ebernoux@octo-etbe.paris.octo
  - user: MFE-key
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDX3lyfpQV3ZMDcyb5t14QOcIhyOLw/nSSqrYQzkdzTdPaDNT9aATEuWPsViAtsOISFZa5uNBJSAb/rdCkJDY5CqPlNR1nVumDT0OR8PCZIAlpfLVGJkXCyEZ+DHyyzKcT2lFwNmDLYVgqu64UYqjonhSDjvafTIaE/wetyDwbSRTkcHtqtxLJ553nrskm6M5TauUh4b/D3ItpcWtj1N/pJSpl6+p3vx+WbU1uK3Oz9JGjA6/g4eO215GQRLybCpbk64HYzdvaVaujlM7uPPyxpJkR7+sUIbTja4HBIBwTW90HLmFvo3vXAFwmlzBfC1rQM5WkbWwjjB/CuuEYaqsrR Matthias Feraga <mferaga@octo.com>
  - user: LUM-key
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkU8CyvmUoDvYdVuZpudo8/mnzP02BT8ADNEWpi1Kif0b6cgpk17u40G2kWTYoibOXhPMb5kNA71VMJTEjXtSziSpdXsev0DdKHcJq02shWj8D0+qXf6GL9tfjhr7vkpTQqQD5pnonia114kp3u4H2c02n1afLiMPGy+Zhphv0RCDE99jmqkIRPf5otFTVDEP1SqjRQo7mIoSKaKEv4f8Fak6N3gS7ZRrUNnQsXwFnWOVUF7XRmplmKtRSt3MKbJ8X2P21Vc1b3tN7FexygKCg39168G6M07w5i/h9EFwYTHz05WDoInk8qz03VJ4smJYrMpxLPWyfFnp785ud1JPn lucien@MacBook-Pro-de-Lucien.localssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeRP6nqjIXVua+yJznjEKnuu6oQ5B5lOoatMKFtmvIkNz8VcOrNt4WtrIF5kgEt3dg5fV/vEIHztmHISiD9sBeJHUcOX2Z7R+bpLxHIVMFY4LSg27fTWIZbDEcl7IQBe/pfFER6B2IZt4cMlRXiN63JWmnSNbPjIyc17L6NmFTQ9FMZNJvXUDXROANTI1ZMJTft0aNFdtS1JWEZ09Aw1LQDrsrIa3ZTtfUJjc6F8bDHICZr8COEpsdd/qFuD6d64ejVwUQBIikjZCIUEAsGRh08ezPnrFql33Cy/w9FyunO6my6ym9JA0vNi0FCmzkzmkJA3Cf4cozTmjdtb1v1/PTmQl9cgnJc9g97SfG1ih2OqojiD/7RwwtdGPzW5CUZg0BBS0GBpPgm5I7i5hgZxDlBc5KSTbjP/wfhVAFD73zmEPhDtNtJbpALRVc4RdCOG3iK9ZDm94fJFz+PRlKU+5CtzasfjDulTCvPUZNUFNvIbkSI/9OzZDEqkW7vfEDcMB6qqfkF6Ni2RtVkDRKVwqtHNdC3XcM+zbtUPtvFW874iVb6MZieuFUnevzxVZjjSBPRaTsrkDVDjhJXNk8sxi0KMVFNOv+mcaYbACbHacPlBLjNOJsvVB6DolfJUyGRqubdneWWabmD6XVtH/uyKJKT3/TLPc3pNiYxHlMC/x9HQ== lucien@MacBook-Pro-de-Lucien.local

htpasswd_credentials:
  - path: /etc/nginx/passwdfile
    name: dinsic
    password: 'supersecure'
    owner: root
    group: www-data
    mode: 'u+rw,g+r'


#Nginx conf
nginx_user: "www-data"
nginx_remove_default_vhost: True
nginx_vhosts:
  - listen: 80
    server_name: "{{ inventory_hostname }}"
    return: 301 https://$server_name$request_uri
  - listen: "443 ssl http2"
    server_name: "{{ inventory_hostname }}"
    root: "/var/www/html"
    index: "index.html index.nginx-debian.html"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    error_page: "404 /404/index.html"
    filename: "dinsic.conf"
    extra_parameters: |
      location / {
          auth_basic           "Nginx with basic auth.";
          auth_basic_user_file /etc/nginx/passwdfile;
          }
      ssl_certificate     /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      ssl_protocols       TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;


#Certbot
certbot_auto_renew_user: root
certbot_auto_renew_minute: 20
certbot_auto_renew_hour: 5
certbot_admin_email: ebernoux@octo.com
certbot_create_if_missing: yes
certbot_create_standalone_stop_services: []
certbot_certs:
  - domains:
      - "{{ inventory_hostname }}"



